      <form class="formulario form-theme pt-5 h-100"
      name="formContacto" id="formContacto" onSubmit="formReset()">
        <div class="text-center titulo py-3">
        <!-- Envíanos tus Datos -->
          <h2 class="t-vinkel fw-700 h3 mb-0">Solicita tu Asesoría Aquí</h2>
        </div>
          <div class="col-12 form-row py-5 px-3">

            <div class="d-inline d-lg-flex text-left col-12 mb-3">
              <div class="campo_t d-flex align-items-center col-12 col-lg-4 f-vinkel-regular text-white my-auto">Nombre y Apellidos:</div>
              <div class="col-12 col-lg-8">
                <input type="text" class="form-control rounded-pill rounded-0 border-0" name="nombre" id="nombre" placeholder="Ingresa tus datos" required="Campo obligatorio">
              </div>
            </div>

            <div class="d-inline d-lg-flex text-left col-12 mb-3">
              <div class="campo_t d-flex align-items-center col-12 col-lg-4 f-vinkel-regular text-white my-auto">Carrera Profesional:</div>
              <div class="col-12 col-lg-8">
                <input type="text" class="form-control rounded-pill rounded-0 border-0" name="carrera" id="carrera" placeholder="Ingresa tu carrera profesional" required="Campo obligatorio">
              </div>
            </div>

            <div class="d-inline d-lg-flex text-left col-12 mb-3">
              <div class="campo_t d-flex align-items-center col-12 col-lg-4 f-vinkel-regular text-white my-auto">Celular:</div>
              <div class="col-12 col-lg-8">
                <input type="tel" class="form-control rounded-pill rounded-0 border-0" onkeypress='return validaNumericos(event)' name="celular" id="celular" placeholder="Ingresa tu celular" maxlength="9" required="Campo obligatorio">
              </div>
            </div>

            <div class="d-inline d-lg-flex text-left col-12 mb-3">
              <div class="campo_t d-flex align-items-center col-12 col-lg-4 f-vinkel-regular text-white my-auto">Grado a Obtener:</div>
              <div class="col-12 col-lg-8">
                <input type="text" class="form-control rounded-pill rounded-0 border-0" name="grado" id="grado" placeholder="Ingresa tu grado a obtener" required="Campo obligatorio">
              </div>
            </div>

            <div class="d-inline d-lg-flex text-left col-12 mb-3">
              <div class="campo_t d-flex align-items-center col-12 col-lg-4 f-vinkel-regular text-white my-auto">Correo:</div>
              <div class="col-12 col-lg-8">
                <input type="email" class="form-control rounded-pill rounded-0 border-0" name="email" id="email" placeholder="Ingresa tu correo" required="Campo obligatorio">
              </div>
            </div>
          </div>
          <div class="w-100 mb-4 text-center pb-5" style="left: 0;">
              <button class="btn btn-danger t-montserrat fw-600 text-white px-4 px-md-5 text-uppercase rounded-pill">
                Enviar
              </button>
            </div>
            <div class="text-right">
            <h2 class="f-vinkel-regular h5 text-white fw-400 mx-3 mb-3">#QUÉDATEENCASA</h2>
            </div>
      </form>

      <div id="alertConfirmPrincipal">
          <p id="msg"></p>
      </div>

      <script type="text/javascript">
        function formReset(){
          setTimeout('document.formContacto.reset()', 1000);
          alert("Datos enviados exitosamente");
          window.location='mensaje.php';
          return false;
        }
        function validaNumericos(event) {
            if(event.charCode >= 48 && event.charCode <= 57){
              return true;
             }
             return false;
        }
      </script>